theme: jekyll-theme-minimal
title: StockTheHouse's Github
description: This page is a centralized pretty version of my github account.  It covers portfolio projects, code tool boxs, games made in python, labds for anyone to try (or improve) and will keep getting more things.  Thanks for stopping by


