theme: jekyll-theme-slate
title: StockTheHouse's Github
description: |
  Welcome to my GitHub portfolio! Here, you'll find my best projects, tools, 
  Python games, and interactive labs for anyone to try (or improve).  
  Expect updates as I keep adding cool stuff. Thanks for stopping by!
